## board
### IP TEST
GET http://localhost:3000/

### 게시글 전체 조회
GET http://localhost:3000/board

### 게시글 단건 조회
GET http://localhost:3000/board/4

### 게시글 생성
POST http://localhost:3000/board
Content-Type: application/json

{
  "title": "test#1010",
  "contents": "post test"
}

### 게시글 수정
PUT http://localhost:3000/board/5
Content-Type: application/json

{
  "title": "test#5-updated",
  "contents": "put test"
}

### 게시글 삭제
DELETE http://localhost:3000/board/3